### ISSUE TITLE
Employ dependabot?

### ISSUE THREAD

**Issue by honzajavorek** [zitkino/zitkino#13]
I'm getting GitHub Alerts about the repo quite regularly. If the code base can be automatically tested by GitHub Actions under Pull Requests, so that the updates are confident, would it make sense to employ https://dependabot.com/ to automatically update the dependencies? It can auto-merge PRs if the tests pass.

If there are no tests or there is no manpower to do something like this on the project, feel free to close the issue. It's just an idea.

**Comment by hermajan** [comment]
Dependabot is employed in this repository. When it creates pull request I try to merge it soon as possible. But sometimes it fails to create pull requests automatically. Lots of it is when some unimportant javascript library used only for building the project needs update. So I update it later when there is some bigger update.

Some tests would be great to have but currently I did not prioritize it. Maybe I can create them for backend part of project but I don't know how test automatically javascript dependencies on which Dependabot complains.

**Comment by honzajavorek** [comment]
Ah, ok! Makes sense, thanks for the details. Keep up the good work :)
