### ISSUE TITLE
Kino Scala+Scala nemá aktuální program

### ISSUE THREAD

**Issue by kudlav** [zitkino/zitkino#28]
## Neaktuální:
- U kina Scala je z celého programu pouze jedna nefilmová akce: https://www.zitkino.cz/kino/scala
- Kino Art nemá program vůbec: https://www.zitkino.cz/kino/art

## Chybějící kina:
- [Letní kino Filda](https://www.letnaky.cz/filda)
- [Letní kino na Hvězdárně](https://www.letnaky.cz/hvezdarna-brno)
- [Letní kino na Vlněně](https://www.letnaky.cz/vlnena-brno)
- [Scalní letňák: Janáček](https://www.kinoscala.cz/?cinema=5&hall=26)

**Comment by hermajan** [comment]
Děkuji za upozornění. Opraveno a přidány nové kina 🙂
